import type { Metadata } from "next";
import "./globals.css";
import { DM_Sans } from "next/font/google"
import Providers from "./providers";


const dm_Sans = DM_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-dm-sans"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${dm_Sans.className}`}
      >
        <Providers>

          {children}

        </Providers>
      </body>
    </html>
  );
}
